[package]
name = "svd_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.82"
wasm-bindgen = "0.2.95"

[package.metadata.wasm-bindgen]
externref-table-size = 4096
reference-types = false
